version: "2"

services:

  jenkins:
    image: jenkins
    networks:
      - devonfwshopfloor
    volumes:
      - devonfw_shop_floor_jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"

  nexus:
    image: sonatype/nexus
    networks:
      - devonfwshopfloor
    volumes:
      - devonfw_shop_floor_nexus_data:/sonatype-work
    ports:
      - "8081:8081"

  sonarqube:
    image: sonarqube
    ports:
      - "8082:9000"
    networks:
      - devonfwshopfloor
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - devonfw_shop_floor_sonarqube_conf:/opt/sonarqube/conf
      - devonfw_shop_floor_sonarqube_data:/opt/sonarqube/data
      - devonfw_shop_floor_sonarqube_extensions:/opt/sonarqube/extensions
      - devonfw_shop_floor_sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  db:
    image: postgres
    networks:
      - devonfwshopfloor
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - devonfw_shop_floor_sonarqube_postgresql:/var/lib/postgresql
      - devonfw_shop_floor_sonarqube_postgresql_data:/var/lib/postgresql/data

  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    ports:
      - "8083:80"
    networks:
      - devonfwshopfloor
    restart: always
    volumes:
      - devonfw_shop_floor_gilab_config:/etc/gitlab
      - devonfw_shop_floor_gilab_logs:/var/log/gitlab
      - devonfw_shop_floor_gilab_data:/var/opt/gitlab
      - devonfw_shop_floor_gilab_backups:/var/opt/gitlab/backups

networks:
  devonfwshopfloor:
    driver: bridge

volumes:
  devonfw_shop_floor_jenkins_home:
  devonfw_shop_floor_nexus_data:
  devonfw_shop_floor_sonarqube_conf:
  devonfw_shop_floor_sonarqube_data:
  devonfw_shop_floor_sonarqube_extensions:
  devonfw_shop_floor_sonarqube_bundled-plugins:
  devonfw_shop_floor_sonarqube_postgresql:
  devonfw_shop_floor_sonarqube_postgresql_data:
  devonfw_shop_floor_gilab_config:
  devonfw_shop_floor_gilab_logs:
  devonfw_shop_floor_gilab_data:
  devonfw_shop_floor_gilab_backups: