version: '2'

services:
  nginx-proxy:
    image: 'jwilder/nginx-proxy'
    restart: always
    container_name: 'dsf_reverse_proxy'
    networks:
      - devonfw-shop-floor
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  portainer:
    image: 'portainer/portainer'
    restart: always
    container_name: 'dsf_portainer'
    networks:
      - devonfw-shop-floor
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - './volumes/portainer/data:/data'
    environment:
      - VIRTUAL_HOST=portainer.10.68.26.165.nip.io
      - VIRTUAL_PORT=9000
  jira:
    image: 'blacklabelops/jira'
    restart: always
    container_name: 'dsf_jira'
    networks:
      - devonfw-shop-floor
    volumes:
      - './volumes/jira/data:/var/atlassian/jira'
    environment:
      - VIRTUAL_HOST=jira.10.68.26.165.nip.io
      - VIRTUAL_PORT=8080
  jenkins:
    image: 'jenkins'
    restart: always
    container_name: 'dsf_jenkins'
    networks:
      - devonfw-shop-floor
    volumes:
      - './volumes/jenkins/jenkins_home:/var/jenkins_home'
    environment:
      - VIRTUAL_HOST=jenkins.10.68.26.165.nip.io
      - VIRTUAL_PORT=8080
  nexus:
    image: 'sonatype/nexus'
    restart: always
    container_name: 'dsf_nexus'
    networks:
      - devonfw-shop-floor
    volumes:
      - './volumes/nexus/nexus-data:/sonatype-work'
    environment:
      - VIRTUAL_HOST=nexus.10.68.26.165.nip.io
      - VIRTUAL_PORT=8081
  sonarqube:
    image: 'sonarqube'
    container_name: 'dsf_sonarqube'
    networks:
      - devonfw-shop-floor
    volumes:
      - './volumes/sonarqube/conf:/opt/sonarqube/conf'
      - './volumes/sonarqube/data:/opt/sonarqube/data'
      - './volumes/sonarqube/extensions:/opt/sonarqube/extensions'
      - './volumes/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins'
    environment:
      - VIRTUAL_HOST=sonarqube.10.68.26.165.nip.io
      - VIRTUAL_PORT=9000
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    container_name: 'dsf_gitlab'
    networks:
      - devonfw-shop-floor
    volumes:
      - './volumes/gitlab/etc/gilab:/etc/gitlab'
      - './volumes/gitlab/var/log:/var/log/gitlab'
      - './volumes/gitlab/var/opt:/var/opt/gitlab'
      - './volumes/gitlab/ssl:/etc/ssl/certs/gitlab'
    environment:
      - VIRTUAL_HOST=gitlab.10.68.26.165.nip.io
      - VIRTUAL_PORT=8080
  crucible:
    image: 'mswinarski/atlassian-crucible'
    restart: always
    container_name: 'dsf_crucible'
    networks:
      - devonfw-shop-floor
    volumes:
      - './volumes/crucible/data:/atlassian/data/crucible'
    environment:
      - VIRTUAL_HOST=crucible.10.68.26.165.nip.io
      - VIRTUAL_PORT=8080
  db:
    image: mattermost/mattermost-prod-db
    restart: unless-stopped
    container_name: 'dsf_mattermost_db'
    networks:
      - devonfw-shop-floor
    volumes:
      - './volumes/mattermost/db/var/lib/postgresql/data:/var/lib/postgresql/data'
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
  app:
    image: mattermost/mattermost-prod-app
    restart: unless-stopped
    container_name: 'dsf_mattermost_app'
    networks:
      - devonfw-shop-floor
    volumes:
      - './volumes/mattermost/app/mattermost/config:/mattermost/config:rw'
      - './volumes/mattermost/app/mattermost/data:/mattermost/data:rw'
      - './volumes/mattermost/app/mattermost/logs:/mattermost/logs:rw'
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
  web:
    image: mattermost/mattermost-prod-web
    container_name: 'dsf_mattermost_web'
    networks:
      - devonfw-shop-floor
    restart: unless-stopped
    volumes:
      - './volumes/mattermost/web/cert:/cert:ro'
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=mattermost.10.68.26.165.nip.io
      - VIRTUAL_PORT=80
  dev:
    image: 'tomcat'
    restart: always
    container_name: 'dsf_dev'
    networks:
      - devonfw-shop-floor
    environment:
      - 'JASYPT_ENCRYPTOR_PASSWORD=mirabaud'
      - 'JASYPT_DECRYPTOR_PASSWORD=mirabaud'
    volumes:
      - './volumes/tomcat-dev/webapps:/usr/local/tomcat/webapps/'
      - './volumes/tomcat-dev/logs:/usr/local/tomcat/logs/'
      - './volumes/tomcat-dev/webservicelogs/:/usr/local/logs/'
    environment:
      - VIRTUAL_HOST=dev.10.68.26.165.nip.io
      - VIRTUAL_PORT=8080
  stage:
    image: 'tomcat'
    restart: always
    container_name: 'dsf_stage'
    networks:
      - devonfw-shop-floor
    environment:
      - 'JASYPT_ENCRYPTOR_PASSWORD=mirabaud'
      - 'JASYPT_DECRYPTOR_PASSWORD=mirabaud'
    volumes:
      - './volumes/tomcat-stage/webapps:/usr/local/tomcat/webapps/'
      - './volumes/tomcat-stage/logs:/usr/local/tomcat/logs/'
      - './volumes/tomcat-stage/webservicelogs/:/usr/local/logs/'
    environment:
      - VIRTUAL_HOST=stage.10.68.26.165.nip.io
      - VIRTUAL_PORT=8080

networks:
  devonfw-shop-floor:
    driver: bridge