version: "2"

###############################
# devonfw-shop-floor 4 Docker #
###############################

#######################
#   8080: Jenkins     #
#   8081: Nexus       #
#   8082: GitLab      #
#   8083: SonarQube   #
#   8084: Mattermost  #
#######################

services:

  # #############
  # #  JENKINS  #
  # #############
  jenkins:
    image: jenkins
    volumes:
      - ./jenkins/volumes/jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"

  # ###########
  # #  NEXUS  #
  # ###########
  nexus:
    image: sonatype/nexus
    volumes:
      - ./nexus/volumes/nexus-data:/sonatype-work
    ports:
      - "8081:8081"

  # ############
  # #  GITLAB  #
  # ############
  gitlab_web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG:
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '8082:80'
      - '443:443'
      - '22:22'
    volumes:
      - './mnt/e/gitlab/etc:/etc/gitlab'
      - './mnt/e/gitlab/opt:/var/opt/gitlab'
      - './mnt/e/gitlab/log:/var/log/gitlab'

  ###############
  #  SONARQUBE  #
  ###############
  sonarqube:
    image: sonarqube
    ports:
      - "8083:9000"
    # networks:
    #   - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - ./sonarqube/volumes/sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube/volumes/sonarqube_data:/opt/sonarqube/data
      - ./sonarqube/volumes/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube/volumes/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  sonarqube_db:
    image: postgres
    # networks:
    #   - sonarnet
    environment:
      - POSTGRES_USER=devonfw_user
      - POSTGRES_PASSWORD=devonfw_password
    volumes:
      - ./sonarqube/volumes/postgresql:/var/lib/postgresql
      - ./sonarqube/volumes/postgresql_data:/var/lib/postgresql/data

  ################
  #  MATTERMOST  #
  ################
  # mattermost_db:
  #   build: mattermost
  #     context: ./db
  #   restart: unless-stopped
  #   volumes:
  #     - ./mattermost/volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
  #     - /etc/localtime:/etc/localtime:ro

  #   environment:
  #     - POSTGRES_USER=devonfw_user
  #     - POSTGRES_PASSWORD=devonfw_password
  #     - POSTGRES_DB=devonfw_mattermost
  # mattermost_app:
  #   build:
  #     context: ./mattermost/app
  #     args:
  #       - edition=team
  #   restart: unless-stopped
  #   volumes:
  #     - ./mattermost/volumes/app/mattermost/config:/mattermost/config:rw
  #     - ./mattermost/volumes/app/mattermost/data:/mattermost/data:rw
  #     - ./mattermost/volumes/app/mattermost/logs:/mattermost/logs:rw
  #     - /etc/localtime:/etc/localtime:ro      
  #   environment:
  #     - MM_USERNAME=devonfw_user
  #     - MM_PASSWORD=devonfw_password
  #     - MM_DBNAME=devonfw_mattermost
  # mattermost_web:
  #   build: mattermost
  #     context: ./web
  #   ports:
  #     - "8084:80"
  #     - "443:443"
  #   restart: unless-stopped
  #   volumes:
  #     - ./mattermost/volumes/web/cert:/cert:ro
  #     - /etc/localtime:/etc/localtime:ro

  