version: "2"

###############################
# devonfw-shop-floor 4 Docker #
###############################

services:
  ############
  #  GITLAB  #
  ############
  gitlab_web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
    ports:
      - '80:80'
      - '443:443'
      - '22:22'
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'

  ################
  #  MATTERMOST  #
  ################
  mattermost_db:
    build: mattermost_db
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/localtime:/etc/localtime:ro

    environment:
      - POSTGRES_USER=devonfw_mmuser
      - POSTGRES_PASSWORD=devonfw_mmuser_password
      - POSTGRES_DB=devonfw_mattermost
  mattermost_app:
    build:
      context: mattermost_app
      args:
        - edition=team
    restart: unless-stopped
    volumes:
      # LINUX
      - /c/devonfw/devonfw/CICD/mattermost/volumes/app/mattermost/config:/mattermost/config:rw
      - /c/devonfw/devonfw/CICD/mattermost/volumes/app/mattermost/data:/mattermost/data:rw
      - /c/devonfw/devonfw/CICD/mattermost/volumes/app/mattermost/logs:/mattermost/logs:rw
      - /etc/localtime:/etc/localtime:ro      
    environment:
      - MM_USERNAME=devonfw_mmuser
      - MM_PASSWORD=devonfw_mmuser_password
      - MM_DBNAME=devonfw_mattermost
  mattermost_web:
    build: mattermost_web
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro

