version: "2"

#   8080: Jenkins
#   8081: Nexus
#   8082: GitLab
#   8083: SonarQube
#   8084: Mattermost

services:
  # jenkins
  jenkins:
    image: jenkins
    networks:
      - devonfwshopfloor
    volumes:
      - devonfw_shop_floor_jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"

  # nexus
  nexus:
    image: sonatype/nexus
    networks:
      - devonfwshopfloor
    volumes:
      - devonfw_shop_floor_nexus_data:/sonatype-work
    ports:
      - "8081:8081"

  # sonarqube
  sonarqube:
    image: sonarqube
    ports:
      - "8082:9000"
    networks:
      - devonfwshopfloor
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - devonfw_shop_floor_sonarqube_conf:/opt/sonarqube/conf
      - devonfw_shop_floor_sonarqube_data:/opt/sonarqube/data
      - devonfw_shop_floor_sonarqube_extensions:/opt/sonarqube/extensions
      - devonfw_shop_floor_sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  db:
    image: postgres
    networks:
      - devonfwshopfloor
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - devonfw_shop_floor_sonarqube_postgresql:/var/lib/postgresql
      - devonfw_shop_floor_sonarqube_postgresql_data:/var/lib/postgresql/data

  # gitlab
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    ports:
      - "8083:80"
    networks:
      - devonfwshopfloor
    restart: always
    volumes:
      - devonfw_shop_floor_gilab_config:/etc/gitlab
      - devonfw_shop_floor_gilab_logs:/var/log/gitlab
      - devonfw_shop_floor_gilab_data:/var/opt/gitlab
      - devonfw_shop_floor_gilab_backups:/var/opt/gitlab/backups

  # mattermost
  mattermostdb:
    build: mattermostdb
    restart: unless-stopped
    volumes:
      - devonfw_shop_floor_mattermost_postgresql_data:/var/lib/postgresql/data
      - devonfw_shop_floor_mattermost_localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
  mattermostapp:
    build:
      context: mattermostapp
      args:
        - edition=team
    restart: unless-stopped
    volumes:
      - devonfw_shop_floor_mattermost_config:/mattermost/config:rw
      - devonfw_shop_floor_mattermost_data:/mattermost/data:rw
      - devonfw_shop_floor_mattermost_logs:/mattermost/logs:rw
      - devonfw_shop_floor_mattermost_localtime:/etc/localtime:ro
    environment:
      - MM_USERNAME=mmuser
      - MM_PASSWORD=mmuser_password
      - MM_DBNAME=mattermost
  mattermostweb:
    build: mattermostweb
    ports:
      - "8084:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - devonfw_shop_floor_mattermost_cert:/cert:ro
      - devonfw_shop_floor_mattermost_localtime:/etc/localtime:ro

networks:
  devonfwshopfloor:
    driver: bridge

volumes:
  devonfw_shop_floor_jenkins_home:
  devonfw_shop_floor_nexus_data:
  devonfw_shop_floor_sonarqube_conf:
  devonfw_shop_floor_sonarqube_data:
  devonfw_shop_floor_sonarqube_extensions:
  devonfw_shop_floor_sonarqube_bundled-plugins:
  devonfw_shop_floor_sonarqube_postgresql:
  devonfw_shop_floor_sonarqube_postgresql_data:
  devonfw_shop_floor_gilab_config:
  devonfw_shop_floor_gilab_logs:
  devonfw_shop_floor_gilab_data:
  devonfw_shop_floor_gilab_backups:
  devonfw_shop_floor_mattermost_postgresql_data:
  devonfw_shop_floor_mattermost_config:
  devonfw_shop_floor_mattermost_data:
  devonfw_shop_floor_mattermost_logs:
  devonfw_shop_floor_mattermost_cert:
  devonfw_shop_floor_mattermost_localtime: