nexus:
        image: 'sonatype/nexus'
        restart: always
        volumes:
                - '/nexus-data:/sonatype-work'
sonar:
        image: 'sonarqube'
        ports:
                - '9092:9092'
                - '8086:9000'
        volumes:
                - '/conf:/opt/sonarqube/conf'
                - '/data:/opt/sonarqube/data'
                - '/extensions:/opt/sonarqube/extensions'
                - '/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins'
gitlab:
        image: 'gitlab/gitlab-ce:latest'
        restart: always
        volumes:
                - '/home/devonfw/gitlab/volumes/etc/gilab:/etc/gitlab'
                - '/home/devonfw/gitlab/volumes/var/log:/var/log/gitlab'
                - '/home/devonfw/gitlab/volumes/var/opt:/var/opt/gitlab'
                - '/home/devonfw/gitlab/volumes/ssl:/etc/ssl/certs/gitlab'
crucible:
        image: 'mswinarski/atlassian-crucible'
        restart: always
        volumes:
                - '/home/devonfw/crucible/data:/atlassian/data/crucible'
nginx-proxy:
        image: 'nginx'
        restart: always
        links:
                - nexus:nexus
                - sonar:sonar
                - gitlab:gitlab
                - crucible:crucible
        ports:
                - '8081:8081'
                #- '8086:8086'
                - '8888:8888'
                - '8084:8084'
                - '443:443'
        volumes:
                - './nexus-data/conf/nginx.conf:/etc/nginx/nginx.conf:ro'
                - './nexus-data/ssl/key-no-password.pem:/etc/nginx/ssl.key:ro'
                - './nexus-data/ssl/cert.pem:/etc/nginx/ssl.crt:ro'